### ISSUE TITLE
Default command

### ISSUE THREAD

**Issue by fleed** [jden123/JustCli#20]
Can I define a command executed by default if no argument is provided?

I really like the interface of the library, but I also need executables that you can just `doubleclick` and launch.

**Comment by jden123** [comment]
Now it's not implemented.
Can you use bat file/shortcut for that?

**Comment by fleed** [comment]
Thanks for suggestion @jden123 .
Actually, I have an application that monitors all other apps, and I'm quite sure that I would run into problems adding something like a bat file in between.

I've come up with this workaround:

```csharp
var command = CommandLineParser.Default.ParseCommand(args);
if (command is CommandLineHelpCommand helpCommand)
{
    command = new RunCommand();
}

return command.Execute();
```

Can you foresee any issue with it?

**Comment by jden123** [comment]
I think you can use something like:
```csharp
if (args.Length == 0)
{
  return new RunCommand().Execute();
}

return CommandLineParser.Default.ParseAndExecuteCommand(args);
```
What do you think?

**Comment by fleed** [comment]
Thank you @jden123 , that's a simple and valid solution.
